type: object
description: Provides details about a Rights Management Project and it's associated Entities and Agreements.
properties:
  project:
    $ref: ../schemas/project.yaml
  associations:
    type: object
    properties: 
      agreements:
        type: array
        minItems: 0
        maxItems: 200
        items: 
          type: object
          properties: 
            id: 
              type: string
              format: uuid
              x-nullable: false
              description: Unique Identifier for the Rights Agreement object
              example: 86f3218b-908b-4d20-9d04-7ce9ba6c0593
            name:
              type: string
              description: Agreement Name
              required:
                - name
              x-nullable: false
              example: Agreement Name
      entities:
        type: array
        minItems: 0
        maxItems: 200
        items: 
          type: object
          properties: 
            id: 
              type: string
              format: uuid
              x-nullable: false
              description: Unique Identifier for the Rights Entity object
              example: 86f3218b-908b-4d20-9d04-7ce9ba6c0593
            name:
              type: string
              description: Entity Name
              required:
                - name
              x-nullable: false
              example: Entity Name